# Generated by Django 3.2.4 on 2021-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_img', models.ImageField(upload_to='')),
                ('ca_name', models.CharField(max_length=256)),
                ('ca_actor', models.CharField(default='Actor', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='M_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_img', models.ImageField(upload_to='')),
                ('cr_name', models.CharField(max_length=256)),
                ('cr_actor', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='M_Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_screen', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(upload_to='movie-images')),
                ('M_date', models.DateTimeField()),
                ('M_hour', models.IntegerField()),
                ('M_min', models.IntegerField()),
                ('M_desc', models.TextField(max_length=5000)),
                ('M_cast', models.ManyToManyField(to='MovieApp.M_Cast')),
                ('M_crew', models.ManyToManyField(to='MovieApp.M_Crew')),
                ('M_screen', models.ManyToManyField(to='MovieApp.M_Screen')),
            ],
        ),
    ]
