# Generated by Django 3.2.4 on 2021-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cast',
            name='ca_img',
            field=models.ImageField(upload_to='movie-cast'),
        ),
        migrations.AlterField(
            model_name='m_crew',
            name='cr_img',
            field=models.ImageField(upload_to='movie-crew'),
        ),
    ]
