# Generated by Django 3.2.4 on 2021-06-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_auto_20210610_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_image', models.ImageField(blank=True, null=True, upload_to='multiple-movie-images')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_images', to='MovieApp.movie')),
            ],
        ),
    ]
