# Generated by Django 3.2.4 on 2021-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_auto_20210610_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cast',
            name='ca_as',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
