# Generated by Django 3.2.4 on 2021-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_m_cast_ca_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='M_type',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=256, null=True),
        ),
    ]
