# Generated by Django 3.2.4 on 2021-06-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0007_movie_m_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='M_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_name', models.CharField(max_length=256)),
                ('m_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.m_state')),
            ],
        ),
    ]
