# Generated by Django 3.2.4 on 2021-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_m_city_m_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_state',
            name='st_slug',
            field=models.SlugField(blank=True, max_length=256, null=True, verbose_name=models.CharField(max_length=256)),
        ),
    ]
