# Generated by Django 3.2.4 on 2021-06-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0009_m_state_st_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_state',
            name='st_slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
