# Generated by Django 3.2.4 on 2021-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0011_auto_20210612_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Multiplex_name',
            field=models.ManyToManyField(blank=True, null=True, to='MovieApp.M_multiplex_name'),
        ),
    ]
