# Generated by Django 3.2.4 on 2021-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0012_movie_multiplex_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Multiplex_name',
        ),
        migrations.AddField(
            model_name='m_multiplex_name',
            name='Multiplex_movie',
            field=models.ManyToManyField(blank=True, null=True, to='MovieApp.Movie'),
        ),
    ]
