# Generated by Django 3.2.4 on 2021-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0014_m_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_multiplex_name',
            name='movie_time',
            field=models.ManyToManyField(blank=True, null=True, to='MovieApp.M_time'),
        ),
    ]
