# Generated by Django 3.2.4 on 2021-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0015_m_multiplex_name_movie_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='M_screen',
        ),
        migrations.AddField(
            model_name='m_multiplex_name',
            name='M_screen',
            field=models.ManyToManyField(to='MovieApp.M_Screen'),
        ),
    ]
