# Generated by Django 3.2.4 on 2021-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0016_auto_20210612_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_multiplex_name',
            name='M_screen',
            field=models.ManyToManyField(blank=True, null=True, to='MovieApp.M_Screen'),
        ),
    ]
