# Generated by Django 3.2.4 on 2021-06-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0017_alter_m_multiplex_name_m_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_screen',
            name='multiplex_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.m_multiplex_name'),
            preserve_default=False,
        ),
    ]
