# Generated by Django 3.2.4 on 2021-06-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0018_m_screen_multiplex_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_screen',
            name='multiplex_name',
        ),
    ]
