# Generated by Django 3.2.4 on 2021-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0019_remove_m_screen_multiplex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_multiplex_name',
            name='M_screen',
            field=models.ManyToManyField(blank=True, default='2D', null=True, to='MovieApp.M_Screen'),
        ),
    ]
